# Build stage
FROM node:18-alpine AS builder

ARG VITE_APPWRITE_PROJECT_ID
ARG VITE_APPWRITE_PUBLIC_ENDPOINT
ARG SHOULD_PUSH_TRANSLATION=false
ARG VITE_TRANSLATION_BUCKET_URL
ARG VITE_TRANSLATION_DELIVERY_ID
ARG VITE_APP_TOLGEE_API_URL
ARG VITE_APP_TOLGEE_API_KEY

ENV VITE_APPWRITE_PROJECT_ID=${VITE_APPWRITE_PROJECT_ID}
ENV VITE_APPWRITE_PUBLIC_ENDPOINT=${VITE_APPWRITE_PUBLIC_ENDPOINT}
ENV SHOULD_PUSH_TRANSLATION=${SHOULD_PUSH_TRANSLATION}
ENV VITE_APP_TOLGEE_API_URL=${VITE_APP_TOLGEE_API_URL}
ENV VITE_APP_TOLGEE_API_KEY=${VITE_APP_TOLGEE_API_KEY}
ENV VITE_TRANSLATION_BUCKET_URL=${VITE_TRANSLATION_BUCKET_URL}
ENV VITE_TRANSLATION_DELIVERY_ID=${VITE_TRANSLATION_DELIVERY_ID}

WORKDIR /app

# Install pnpm and dependencies
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Copy the rest of the source code
COPY . .

RUN if [ "$SHOULD_PUSH_TRANSLATION" = "true" ]; then pnpm tgee-push; fi

RUN pnpm run build

# Production stage
FROM node:18-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]