import { type Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types src/types`.

export type Prospects = Models.Document & {
    email: string;
    submit_count: number;
}

export type Feedbacks = Models.Document & {
    email: string;
    userId: string | null;
    message: string;
}

export type Contacts = Models.Document & {
    userId: string | null;
    message: string;
    email: string;
}
