name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read version from package.json
        id: pkg
        run: echo "version=$(node -p \"require('./package.json').version\")" >> "$GITHUB_OUTPUT"
      - name: Check if tag exists
        id: tag
        run: |
          git fetch --tags
          if git rev-parse "v${{ steps.pkg.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Create GitHub release
        if: steps.tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.pkg.outputs.version }}
          name: Release ${{ steps.pkg.outputs.version }}
          generate_release_notes: true
